import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

/** @type {import('eslint').Linter.Config[]} */
const eslintConfig = [
  {
    // Regenerated by `payload generate:types`; not ours to lint.
    ignores: ["payload-types.ts"],
  },
  ...nextCoreWebVitals,
  {
    rules: {
      // Add any custom rules here
    },
  },
];

export default eslintConfig;
